// Generated-file ownership: the marker, the body digest, and the rules for
// when an existing file may be overwritten.
//
// A generated file is exactly: three marker lines, each ending in "\n", then
// the BODY. The third marker line carries sha256(BODY), where BODY is every byte
// after the third line's "\n", as written (UTF-8, LF line endings, ending in
// "\n"). The marker lines themselves are not covered, so the digest never
// includes itself.
//
// The digest is an OVERWRITE / DRIFT GUARD ONLY: it lets `render` tell a file it
// wrote from one somebody edited, so a hand edit is never silently clobbered.
// It is not a signature and not a trust anchor — anyone can edit a file and
// recompute it. Integrity of what runs comes from code review (CODEOWNERS) and
// `render --check`, not from this hash.
import { createHash } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { join } from 'node:path';

import { safeRemove, safeWriteFile } from './safe-path.mjs';

export const MARKER_SCHEMA = '1';
const MARKER_LINE_1 = '# GENERATED by ssd-onboard from .ssd/onboarding.yml. DO NOT EDIT BY HAND.';
const MARKER_LINE_2 = '# Change .ssd/onboarding.yml, then run: ssd-onboard render';
const MARKER_LINE_3 = /^# ssd-onboard: generated schema=(\d+) sha256=([0-9a-f]{64})$/;

export function digest(text) {
  return createHash('sha256').update(text).digest('hex');
}

export function withMarker(body) {
  const normalized = body.endsWith('\n') ? body : `${body}\n`;
  return [
    MARKER_LINE_1,
    MARKER_LINE_2,
    `# ssd-onboard: generated schema=${MARKER_SCHEMA} sha256=${digest(normalized)}`,
    normalized
  ].join('\n');
}

// { marked: false } | { marked: true, intact: boolean, schema }
export function readMarker(text) {
  const lines = text.split('\n');
  if (lines[0] !== MARKER_LINE_1 || lines[1] !== MARKER_LINE_2) {
    return { marked: false };
  }
  const match = MARKER_LINE_3.exec(lines[2] ?? '');
  if (!match) {
    return { marked: true, intact: false, schema: null };
  }
  const body = lines.slice(3).join('\n');
  return { marked: true, intact: digest(body) === match[2], schema: match[1] };
}

// --- a small line diff (LCS), enough to review generated changes ----------------

export function lineDiff(before, after, { context = 3, from = 'current', to = 'rendered' } = {}) {
  const a = before === null ? [] : before.split('\n');
  const b = after === null ? [] : after.split('\n');
  const n = a.length;
  const m = b.length;
  const table = Array.from({ length: n + 1 }, () => new Uint32Array(m + 1));
  for (let i = n - 1; i >= 0; i -= 1) {
    for (let j = m - 1; j >= 0; j -= 1) {
      table[i][j] = a[i] === b[j] ? table[i + 1][j + 1] + 1 : Math.max(table[i + 1][j], table[i][j + 1]);
    }
  }
  const ops = [];
  let i = 0;
  let j = 0;
  while (i < n || j < m) {
    if (i < n && j < m && a[i] === b[j]) {
      ops.push({ type: ' ', text: a[i] });
      i += 1;
      j += 1;
    } else if (i < n && (j >= m || table[i + 1][j] >= table[i][j + 1])) {
      // Removals before additions, as in a conventional diff.
      ops.push({ type: '-', text: a[i] });
      i += 1;
    } else {
      ops.push({ type: '+', text: b[j] });
      j += 1;
    }
  }
  if (!ops.some((op) => op.type !== ' ')) {
    return '';
  }
  const keep = new Array(ops.length).fill(false);
  ops.forEach((op, index) => {
    if (op.type !== ' ') {
      for (let k = Math.max(0, index - context); k <= Math.min(ops.length - 1, index + context); k += 1) {
        keep[k] = true;
      }
    }
  });
  const out = [`--- ${from}`, `+++ ${to}`];
  let skipping = false;
  ops.forEach((op, index) => {
    if (keep[index]) {
      out.push(`${op.type}${op.text}`);
      skipping = false;
    } else if (!skipping) {
      out.push('@@');
      skipping = true;
    }
  });
  return `${out.join('\n')}\n`;
}

// --- the write plan -------------------------------------------------------------------

// Decides, for every rendered file, what `render` may do with it.
//   create     absent
//   unchanged  identical bytes
//   update     ssd-onboard owns it (marker, digest intact) and the content changed
//   forced     hand-edited generated file, overwrite requested with --force <path>
//   adopted    human-owned file, overwrite requested with --adopt <path>
//   conflict   refused: hand-edited generated file, or a human-owned file
export async function planWrites(root, rendered, { adopt = [], force = [] } = {}) {
  const plan = [];
  for (const file of rendered) {
    let current = null;
    try {
      current = await readFile(join(root, file.path), 'utf8');
    } catch (error) {
      if (error.code !== 'ENOENT') {
        throw error;
      }
    }
    const entry = { ...file, current, diff: lineDiff(current, file.content, { from: `a/${file.path}`, to: `b/${file.path}` }) };
    if (current === null) {
      entry.action = 'create';
    } else if (current === file.content) {
      entry.action = 'unchanged';
    } else {
      const marker = readMarker(current);
      if (marker.marked && marker.intact) {
        entry.action = 'update';
      } else if (marker.marked) {
        entry.action = force.includes(file.path) ? 'forced' : 'conflict';
        entry.reason = 'generated file was edited by hand (its digest no longer matches); change .ssd/onboarding.yml instead, or pass --force ' + file.path + ' after reviewing the diff';
      } else {
        entry.action = adopt.includes(file.path) ? 'adopted' : 'conflict';
        entry.reason = 'file exists and was not generated by ssd-onboard; review the diff, then pass --adopt ' + file.path + ' to let ssd-onboard own it';
      }
    }
    plan.push(entry);
  }
  return plan;
}

// Generated files (intact marker) that the current render no longer produces.
export function staleGenerated(workflows, rendered) {
  const renderedPaths = new Set(rendered.map((file) => file.path));
  return workflows.filter((workflow) => workflow.marker.marked && !renderedPaths.has(workflow.path));
}

export async function applyWrites(root, plan) {
  if (plan.some((entry) => entry.action === 'conflict')) {
    throw new Error('refusing to write while any file is in conflict');
  }
  const written = [];
  for (const entry of plan) {
    if (['create', 'update', 'forced', 'adopted'].includes(entry.action)) {
      // Confined: entry.path is rendered, but the checkout it lands in is not
      // trusted (see safe-path.mjs).
      await safeWriteFile(root, entry.path, entry.content);
      written.push(entry.path);
    }
  }
  return written;
}

export async function removeFile(root, path) {
  await safeRemove(root, path);
}
